# Generated by Django 3.0.3 on 2020-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_mynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='myTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_sub', models.CharField(max_length=100)),
                ('task_desc', models.TextField()),
                ('uploading_date', models.CharField(max_length=15)),
                ('deadline', models.CharField(max_length=15)),
            ],
        ),
    ]
